name: Check version updated

on:
  pull_request:
    branches: [ master ]

jobs:
  version_check:
    runs-on: ubuntu-latest
    name: Checks _version.py and CHANGELOG.rst files have been updated
    steps:
    - name: Version check action
      uses: mwcodebase/versioning-checker@v2.2
      with:
        tracked_files: 'pitci/_version.py,CHANGELOG.rst'
